### ISSUE TITLE
Rebuild for Python 3.11?

### ISSUE THREAD

**Issue by meridionaljet** [conda-forge/windspharm-feedstock#25] opened 2023-02-19 22:44 UTC
### Comment:

Python 3.11 has been out for several months now -- any plans to rebuild Windspharm / Pyspharm for this version? This is currently the only hold-out in my standard geospatial stack.

**Comment by ocefpaf** [comment] 2023-02-20 18:51
If you know how to fix https://github.com/conda-forge/pyspharm-feedstock/pull/22 we can probably make this work.

**Comment by meridionaljet** [comment] 2023-02-21 00:38
Well, I'm just a user of the package without deep knowledge of its source, but I can tell you this is the failure that occurs when trying to `pip install pyspharm` within a Python 3.11 environment:

```
        273 |       call lfim1(init,theta,l,n,nm,id,pb,wlfim,wlfim(iw1),
            |                      1
      Error: Rank mismatch in argument ‘theta’ at (1) (rank-1 and scalar)
      src/alf.f:465:22:

        465 |       call lfin1(init,theta,l,m,nm,id,pb,wlfin,wlfin(iw1),
            |                      1
      Error: Rank mismatch in argument ‘theta’ at (1) (rank-1 and scalar)
      INFO: gfortran:f77: build/src.linux-x86_64-3.11/src/_spherepack-f2pywrappers.f
      error: Command "/usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops -Ibuild/src.linux-x86_64-3.11/build/src.linux-x86_64-3.11/src -I/home/user/micromamba/envs/test/lib/python3.11/site-packages/numpy/core/include -Ibuild/src.linux-x86_64-3.11/numpy/distutils/include -I/home/user/micromamba/envs/test/include/python3.11 -c -c src/alf.f -o build/temp.linux-x86_64-cpython-311/src/alf.o" failed with exit status 1
      INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : gcc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : -msse -msse2 -msse3
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> /tmp/pip-install-ik2b_ark/pyspharm_cf6ec7e43d5e4ba59ae725a1c8103a0b/build/temp.linux-x86_64-cpython-311/ccompiler_opt_cache_ext.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyspharm

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by ocefpaf** [comment] 2023-02-21 20:24
> but I can tell you this is the failure that occurs when trying to `pip install pyspharm` within a Python 3.11 environment

Yep. The package is quite old and making it Python 3.11 ready is not an easy (t)ask.

**Comment by matrss** [comment] 2023-04-05 10:02
> but I can tell you this is the failure that occurs when trying to `pip install pyspharm` within a Python 3.11 environment:

I get the same error in a python 3.9 environment and when compiling spherepack itself with a recent gfortran installed via mamba. I was able to compile spherepack (with a few warnings) by adding `-std=legacy` to the gfortran command, so this seems to be caused by changes in the defaults of a more recent fortran compiler. I am not quite sure yet how this would need to be incorporated into this and/or pyspharm's conda feedstock though.

**Comment by zmoon** [comment] 2024-08-08 17:01
With https://github.com/conda-forge/pyspharm-feedstock/pull/22 merged, this should be achievable.

**Comment by ocefpaf** [comment] 2024-11-11 17:04
Made it noarch, so it will be installed in the same envs that pyspharm is. Any request from extra Python versions should be made at the pyspharam feedstock (or repo b/c the software doesn't build well on Python 3.12 yet.)

**Closed as completed by ocefpaf** 2024-11-11 17:04 UTC
Labels: question
